### ISSUE TITLE
DeprecationWarning: '_app_ctx_stack'

### ISSUE THREAD

**Issue by psi29a** [Unleash/Flask-Unleash#19]
```
venv/lib/python3.11/site-packages/flask_unleash/__init__.py:3: DeprecationWarning: '_app_ctx_stack' is deprecated and will be removed in Flask 2.4.
    from flask import current_app, _app_ctx_stack  # type: ignore
```

Considering that Flask 3.0 has been released already; this will be problematic for the use of Unleash with Flask.
https://github.com/pallets/flask/releases

The above has been removed with this https://github.com/pallets/flask/pull/5223 so Flask-Unleash is currently broken for 3.0.

**Comment by sighphyre** [comment]
This got fixed, thank you for raising this one

**Comment by kgaikwad** [comment]
@sighphyre  - could you confirm - will be possible to release minor release with fix for it or already in progress?
